# -*- coding: utf-8 -*-
"""streamapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H8nsqBLbf_eCr8JGwsq_YsZvIH0ehRx_
"""

# Install streamlit
!pip install streamlit

# Now, you can import and use streamlit
import streamlit as st
import pickle
import re
import string

# Load the trained model and vectorizer
with open("/content/spam_classifier (2).pkl", "rb") as model_file:
    model = pickle.load(model_file)

# Text preprocessing function (same as used during training)
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans("", "", string.punctuation))
    return text

# Streamlit app UI
st.set_page_config(page_title="Spam Classifier", page_icon="📧")
st.title("📧 Spam Message Classifier")
st.write("This app classifies whether a message is **spam** or **not spam** (ham) using a trained Naive Bayes model.")

# Text input
user_input = st.text_area("Enter your message here:")

if st.button("Predict"):
    if user_input.strip() == "":
        st.warning("Please enter a message to classify.")
    else:
        # Preprocess and predict
        cleaned_text = preprocess_text(user_input)
        prediction = model.predict([cleaned_text])[0]
        probas = model.predict_proba([cleaned_text])[0]

        st.subheader("Prediction:")
        st.success(f"This message is **{prediction.upper()}**")

        st.subheader("Confidence:")
        st.write(f"🟢 Ham: {probas[model.classes_.tolist().index('ham')]:.2f}")
        st.write(f"🔴 Spam: {probas[model.classes_.tolist().index('spam')]:.2f}")